additions for bot.js
nspacestd/hekbot pull request #2
Opened 2016-11-04 23:10 UTC by aliasfalse

send help to DM, auto-delete after 5 seconds

2016-11-05 09:02 UTC, nspacestd requested changes

2016-11-05 09:02 UTC, nspacestd commented on bot.js
> +    user.sendMessage('Available sounds:\n```\n' + commandList + '```').then(msg => message.delete(5000));
`msg => message.delete(5000)` should be changed to `() => message.delete(5000)` so that the function doesn't have an unused parameter.

2016-11-05 21:13 UTC, TobiTenno commented on bot.js
> +    user.sendMessage('Available sounds:\n```\n' + commandList + '```').then(msg => message.delete(5000));
changed

2016-11-06 11:48 UTC, nspacestd approved these changes

2016-11-06 11:49 UTC, merged